/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TELEMETRY_PB_H_INCLUDED
#define PB_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ProtoData {
    uint32_t device_id;
    float time;
    float ax;
    float ay;
    float az;
    float wx; /* velocidade angular em X */
    float wy; /* velocidade angular em Y */
    float wz; /* velocidade angular em Z */
    float pitch;
    float roll;
    float yaw;
} ProtoData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ProtoData_init_default                   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define ProtoData_init_zero                      {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ProtoData_device_id_tag                  1
#define ProtoData_time_tag                       2
#define ProtoData_ax_tag                         3
#define ProtoData_ay_tag                         4
#define ProtoData_az_tag                         5
#define ProtoData_wx_tag                         6
#define ProtoData_wy_tag                         7
#define ProtoData_wz_tag                         8
#define ProtoData_pitch_tag                      9
#define ProtoData_roll_tag                       10
#define ProtoData_yaw_tag                        11

/* Struct field encoding specification for nanopb */
#define ProtoData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   device_id,         1) \
X(a, STATIC,   SINGULAR, FLOAT,    time,              2) \
X(a, STATIC,   SINGULAR, FLOAT,    ax,                3) \
X(a, STATIC,   SINGULAR, FLOAT,    ay,                4) \
X(a, STATIC,   SINGULAR, FLOAT,    az,                5) \
X(a, STATIC,   SINGULAR, FLOAT,    wx,                6) \
X(a, STATIC,   SINGULAR, FLOAT,    wy,                7) \
X(a, STATIC,   SINGULAR, FLOAT,    wz,                8) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch,             9) \
X(a, STATIC,   SINGULAR, FLOAT,    roll,             10) \
X(a, STATIC,   SINGULAR, FLOAT,    yaw,              11)
#define ProtoData_CALLBACK NULL
#define ProtoData_DEFAULT NULL

extern const pb_msgdesc_t ProtoData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ProtoData_fields &ProtoData_msg

/* Maximum encoded size of messages (where known) */
#define ProtoData_size                           56
#define TELEMETRY_PB_H_MAX_SIZE                  ProtoData_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
